apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: autotest-dis
  namespace: mo-autotest
spec:
  nodeSelector:
    role: benchmark-regression
  dn:
    cacheVolume:
      size: 100Gi
    sharedStorageCache:
      memoryCacheSize: 1Gi
      diskCacheSize: 100Gi
    config: |
      [dn.Txn.Storage]
      backend = "TAE"
      log-backend = "logservice"
      [dn.Ckp]
      flush-interval = "60s"
      min-count = 100
      scan-interval = "5s"
      incremental-interval = "60s"
      global-interval = "100000s"
      [log]
      level = "info"
      format = "json"
      max-size = 512
      [dn.LogtailServer]
      rpc-max-message-size = "16KiB"
      rpc-payload-copy-buffer-size = "16KiB"
      rpc-enable-checksum = true
      logtail-collect-interval = "2ms"
      logtail-response-send-timeout = "10s"
      max-logtail-fetch-failure = 5
    replicas: 1
    resources:
      requests:
        cpu: 15
        memory: 50Gi
  imageRepository: matrixorigin/matrixone
  logService:
    replicas: 3
    resources:
      requests:
        cpu: 15
        memory: 50Gi
    sharedStorage:
      s3:
        path: mo-ares/mo-auto/
        s3RetentionPolicy:  Delete
        secretRef:
          name: aws-auto
    volume:
      size: 100Gi
      storageClassName: gp3-10000
    config: |
      [log]
      level = "info"
      format = "json"
      max-size = 512
  tp:
    cacheVolume:
      size: 100Gi
    sharedStorageCache:
      memoryCacheSize: 8Gi
      diskCacheSize: 1
    config: |
      [cn.Engine]
      type = "distributed-tae"
      [cn.rpc]
      max-message-size = "100M"
      [log]
      level = "info"
      format = "json"
      max-size = 512
      [cn]
      turn-on-push-model = true
      [cn.txn]
      enable-sacrificing-freshness = true
      enable-cn-based-consistency = true
    replicas: 2
    resources:
      requests:
        cpu: 15
        memory: 50Gi
  version: imagetag
